
package org.whl.service.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;

import javax.xml.namespace.QName;

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.interceptor.LoggingInInterceptor;
import org.apache.cxf.interceptor.LoggingOutInterceptor;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-05T15:42:23.197+08:00
 * Generated source version: 3.1.1
 *
 */
public final class ES4SmSr_SmSrES4Port_Client {

    private static final QName SERVICE_NAME = new QName("http://namespaces.gsma.org/esim-messaging/1", "ES4SmSrService");

    private ES4SmSr_SmSrES4Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL =
                ES4SmSrService.class.getClassLoader().getResource("wsdl/20150611/ES4_SMSR.wsdl");

        ES4SmSrService ss = new ES4SmSrService(wsdlURL, SERVICE_NAME);
        ES4SmSr port = ss.getSmSrES4Port();

        Client client = ClientProxy.getClient(port);
        client.getInInterceptors().add(new LoggingInInterceptor());
        client.getOutInterceptors().add(new LoggingOutInterceptor());

        {
            // System.out.println("Invoking es4AuditEIS...");
            // org.whl.service.client.ES4AuditEISRequest _es4AuditEIS_parameters =
            // new ES4AuditEISRequest();
            //
            // _es4AuditEIS_parameters.setFunctionCallIdentifier("1234");
            //
            // _es4AuditEIS_parameters.setEid("123456".getBytes());
            //
            // _es4AuditEIS_parameters.getIccid().add("89123456789");
            //
            // port.es4AuditEIS(_es4AuditEIS_parameters);

        }

        {
            System.out.println("Invoking es4PrepareSMSRChange...");
            ES4PrepareSMSRChangeRequest preSMSRChangeReq = new ES4PrepareSMSRChangeRequest();
            preSMSRChangeReq.setCurrentSmsrId("12.34.56x");
            preSMSRChangeReq.setEid("123456".getBytes());
            preSMSRChangeReq.setFunctionCallIdentifier("1234");

            port.es4PrepareSMSRChange(preSMSRChangeReq);

            System.out.println("Ending invoking es4PrepareSMSRChange...");
        }

        System.exit(0);
    }

}
