package org.whl.service.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-05T15:42:23.259+08:00
 * Generated source version: 3.1.1
 *
 */
@WebServiceClient(name = "ES4SmSrService",
 wsdlLocation = "wsdl/20150611/ES4_SMSR.wsdl",
targetNamespace = "http://namespaces.gsma.org/esim-messaging/1")
public class ES4SmSrService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://namespaces.gsma.org/esim-messaging/1", "ES4SmSrService");
    public final static QName SmSrES4Port = new QName("http://namespaces.gsma.org/esim-messaging/1", "SmSrES4Port");
    static {
        URL url = null;
        try {
            url = new URL("wsdl/20150611/ES4_SMSR.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ES4SmSrService.class.getName())
            .log(java.util.logging.Level.INFO,
                    "Can not initialize the default wsdl from {0}", "file:wsdl/20150611/ES4_SMSR.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ES4SmSrService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ES4SmSrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ES4SmSrService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ES4SmSrService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ES4SmSrService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ES4SmSrService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ES4SmSr
     */
    @WebEndpoint(name = "SmSrES4Port")
    public ES4SmSr getSmSrES4Port() {
        return super.getPort(SmSrES4Port, ES4SmSr.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ES4SmSr
     */
    @WebEndpoint(name = "SmSrES4Port")
    public ES4SmSr getSmSrES4Port(WebServiceFeature... features) {
        return super.getPort(SmSrES4Port, ES4SmSr.class, features);
    }

}
