package org.whl.service.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-05T15:42:23.244+08:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://namespaces.gsma.org/esim-messaging/1", name = "ES4SmSr")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ES4SmSr {

    @Oneway
    @Action(input = "http://gsma.com/ES4/eUICCManagement/ES4-PrepareSMSRChange")
    @WebMethod(operationName = "ES4-PrepareSMSRChange")
    public void es4PrepareSMSRChange(
        @WebParam(partName = "parameters", name = "ES4-PrepareSMSRChangeRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1")
        ES4PrepareSMSRChangeRequest parameters
    );

    @WebResult(name = "ES4-UpdateSubscriptionAddressResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1", partName = "parameters")
    @Action(input = "http://gsma.com/ES4/ProfileManagement/ES4-UpdateSubscriptionAddressRequest", output = "http://gsma.com/ES4/ProfileManagement/ES4-UpdateSubscriptionAddressResponse")
    @WebMethod(operationName = "ES4-UpdateSubscriptionAddress")
    public ES4UpdateSubscriptionAddressResponse es4UpdateSubscriptionAddress(
        @WebParam(partName = "parameters", name = "ES4-UpdateSubscriptionAddressRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1")
        ES4UpdateSubscriptionAddressRequest parameters
    );

    @Oneway
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-EnableProfile")
    @WebMethod(operationName = "ES4-EnableProfile")
    public void es4EnableProfile(
        @WebParam(partName = "parameters", name = "ES4-EnableProfileRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1")
        ES4EnableProfileRequest parameters
    );

    @WebResult(name = "ES4-UpdatePolicyRulesResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1", partName = "parameters")
    @Action(input = "http://gsma.com/ES4/ProfileManagement/ES4-UpdatePolicyRulesRequest", output = "http://gsma.com/ES4/ProfileManagement/ES4-UpdatePolicyRulesResponse")
    @WebMethod(operationName = "ES4-UpdatePolicyRules")
    public ES4UpdatePolicyRulesResponse es4UpdatePolicyRules(
        @WebParam(partName = "parameters", name = "ES4-UpdatePolicyRulesRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1")
        ES4UpdatePolicyRulesRequest parameters
    );

    @Oneway
    @Action(input = "http://gsma.com/ES4/eUICCManagement/ES4-SMSRChange")
    @WebMethod(operationName = "ES4-SMSRChange")
    public void es4SMSRChange(
        @WebParam(partName = "parameters", name = "ES4-SMSRChangeRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1")
        ES4SMSRChangeRequest parameters
    );

    @WebResult(name = "ES4-GetEISResponse", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1", partName = "parameters")
    @Action(input = "http://gsma.com/ES4/ProfileManagement/ES4-GetEISRequest", output = "http://gsma.com/ES4/ProfileManagement/ES4-GetEISResponse")
    @WebMethod(operationName = "ES4-GetEIS")
    public ES4GetEISResponse es4GetEIS(
        @WebParam(partName = "parameters", name = "ES4-GetEISRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1")
        ES4GetEISRequest parameters
    );

    @Oneway
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-DisableProfile")
    @WebMethod(operationName = "ES4-DisableProfile")
    public void es4DisableProfile(
        @WebParam(partName = "parameters", name = "ES4-DisableProfileRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1")
        ES4DisableProfileRequest parameters
    );

    @Oneway
    @Action(input = "http://gsma.com/ES4/PlatformManagement/ES4-DeleteProfile")
    @WebMethod(operationName = "ES4-DeleteProfile")
    public void es4DeleteProfile(
        @WebParam(partName = "parameters", name = "ES4-DeleteProfileRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1")
        ES4DeleteProfileRequest parameters
    );

    @Oneway
    @Action(input = "http://gsma.com/ES4/ProfileManagement/ES4-AuditEIS")
    @WebMethod(operationName = "ES4-AuditEIS")
    public void es4AuditEIS(
        @WebParam(partName = "parameters", name = "ES4-AuditEISRequest", targetNamespace = "http://namespaces.gsma.org/esim-messaging/1")
        ES4AuditEISRequest parameters
    );
}
