
package org.whl.service;

import javax.xml.ws.Endpoint;

import org.apache.cxf.interceptor.LoggingInInterceptor;
import org.apache.cxf.interceptor.LoggingOutInterceptor;
import org.apache.cxf.jaxws.EndpointImpl;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-05T14:40:33.317+08:00
 * Generated source version: 3.1.1
 *
 */

public class ES4SmSr_SmSrES4Port_Server{

    protected ES4SmSr_SmSrES4Port_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SmSrES4PortImpl();
        String address = "http://localhost:8080/ES4/ES4SmSrService";
        EndpointImpl ep = (EndpointImpl) Endpoint.publish(address, implementor);

        ep.getServer().getEndpoint().getInInterceptors().add(new LoggingInInterceptor());
        ep.getServer().getEndpoint().getOutInterceptors().add(new LoggingOutInterceptor());
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ES4SmSr_SmSrES4Port_Server();
        System.out.println("Server ready...");

        Thread.sleep(20 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
