
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.whl.service;

import java.util.logging.Logger;

import org.apache.cxf.annotations.SchemaValidation;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-05T14:40:33.224+08:00
 * Generated source version: 3.1.1
 *
 */

@javax.jws.WebService(
        serviceName = "ES4SmSrService",
        portName = "SmSrES4Port",
        targetNamespace = "http://namespaces.gsma.org/esim-messaging/1",
        wsdlLocation = "wsdl/20150611/ES4_SMSR.wsdl",
        endpointInterface = "org.whl.service.ES4SmSr")
@SchemaValidation
public class SmSrES4PortImpl implements ES4SmSr {

    private static final Logger LOG = Logger.getLogger(SmSrES4PortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.whl.service.ES4SmSr#es4PrepareSMSRChange(org.whl.service.ES4PrepareSMSRChangeRequest  parameters )*
     */
    @Override
    public void es4PrepareSMSRChange(ES4PrepareSMSRChangeRequest parameters) {
        LOG.info("Executing operation es4PrepareSMSRChange");
        System.out.println(parameters);
        try {
            System.out
            .println("FunctionCallIdentifier = " + parameters.getFunctionCallIdentifier());
            String eid = new String(parameters.getEid());
            System.out.println("EID= " + eid);

            System.out.println("CurrentSmsrId=" + parameters.getCurrentSmsrId());
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.whl.service.ES4SmSr#es4UpdateSubscriptionAddress(org.whl.service.ES4UpdateSubscriptionAddressRequest  parameters )*
     */
    @Override
    public org.whl.service.ES4UpdateSubscriptionAddressResponse es4UpdateSubscriptionAddress(ES4UpdateSubscriptionAddressRequest parameters) {
        LOG.info("Executing operation es4UpdateSubscriptionAddress");
        System.out.println(parameters);
        try {
            org.whl.service.ES4UpdateSubscriptionAddressResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.whl.service.ES4SmSr#es4EnableProfile(org.whl.service.ES4EnableProfileRequest  parameters )*
     */
    @Override
    public void es4EnableProfile(ES4EnableProfileRequest parameters) {
        LOG.info("Executing operation es4EnableProfile");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.whl.service.ES4SmSr#es4UpdatePolicyRules(org.whl.service.ES4UpdatePolicyRulesRequest  parameters )*
     */
    @Override
    public org.whl.service.ES4UpdatePolicyRulesResponse es4UpdatePolicyRules(ES4UpdatePolicyRulesRequest parameters) {
        LOG.info("Executing operation es4UpdatePolicyRules");
        System.out.println(parameters);
        try {
            org.whl.service.ES4UpdatePolicyRulesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.whl.service.ES4SmSr#es4SMSRChange(org.whl.service.ES4SMSRChangeRequest  parameters )*
     */
    @Override
    public void es4SMSRChange(ES4SMSRChangeRequest parameters) {
        LOG.info("Executing operation es4SMSRChange");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.whl.service.ES4SmSr#es4GetEIS(org.whl.service.ES4GetEISRequest  parameters )*
     */
    @Override
    public org.whl.service.ES4GetEISResponse es4GetEIS(ES4GetEISRequest parameters) {
        LOG.info("Executing operation es4GetEIS");
        System.out.println(parameters);
        try {
            org.whl.service.ES4GetEISResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.whl.service.ES4SmSr#es4DisableProfile(org.whl.service.ES4DisableProfileRequest  parameters )*
     */
    @Override
    public void es4DisableProfile(ES4DisableProfileRequest parameters) {
        LOG.info("Executing operation es4DisableProfile");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.whl.service.ES4SmSr#es4DeleteProfile(org.whl.service.ES4DeleteProfileRequest  parameters )*
     */
    @Override
    public void es4DeleteProfile(ES4DeleteProfileRequest parameters) {
        LOG.info("Executing operation es4DeleteProfile");
        System.out.println(parameters);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.whl.service.ES4SmSr#es4AuditEIS(org.whl.service.ES4AuditEISRequest  parameters )*
     */
    @Override
    public void es4AuditEIS(ES4AuditEISRequest parameters) {
        LOG.info("Executing operation es4AuditEIS");
        System.out.println(parameters);
        try {
            System.out
            .println("FunctionCallIdentifier = " + parameters.getFunctionCallIdentifier());
            String eid = new String(parameters.getEid());
            System.out.println("EID= " + eid);

            for (String iccid : parameters.getIccid()) {

                System.out.println("ICCID = " + iccid);
            }

        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
